create table if not exists public.battery_rows (
  id bigint generated by default as identity primary key,
  bilmerke text,
  modell text,
  fra_aar integer,
  til_aar integer,
  motortype text,
  ah integer,
  cca integer,
  dimensjon text,
  polplassering text,
  batteritype text,
  varenummer text,
  source_file_name text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
